services:
  bookmarkman:
    image: bookmarkman:latest
    ports:
      - 5001:5001

  nginx:
    image: nginx:1.27
    ports:
      - 8080:8080
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
