# Generated by Django 4.2.20 on 2025-03-23 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookmarks', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookmark',
            old_name='user_id',
            new_name='user',
        ),
    ]
